apiVersion: v1
kind: Secret
metadata:
  name: techfood-api-secret
  namespace: techfood
  labels:
    app.kubernetes.io/name: techfood-api
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: techfood-system
type: Opaque
stringData:
  ConnectionStrings__DataBaseConection: "Server=techfood-sqlserver.cli9gqyj0nsn.us-east-1.rds.amazonaws.com;Database=dbtechfood;User Id=admin;Password=TechFood123!;TrustServerCertificate=True;"
  Jwt__Key: "MmUzYjQtOGM1Zi00YTBkLThiMWYtN2EyYzlkNmUzYjRm"
  Payments__MercadoPago__AccessToken: "APP_USR-5808215342931102-042817-5d5fee5e46fe9a6b08d17f29e741091f-2414323212"
